version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/trade_marketplace
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/applicationstart.sh
      timeout: 300
