version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/trade_marketplace
hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/applicationstart.sh
      timeout: 300
      runas: ubuntu