version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/trade_marketplace
hooks:
  ApplicationStop:
    - location: scripts/applicationstop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/applicationstart.sh
      timeout: 300
      runas: ec2-user